<?php

namespace App\Http\Traits;

trait FieldsTrait
{
    static $client = [
        "appointment_gender_preference",
        "birth_date",
        "country",
        "creation_date",
        "first_appointment_date",
        "first_name",
        "is_company",
        "is_prospect",
        "last_name",
        "liability_release",
        "membership_icon",
        "mobile_provider",
        "notes",
        "state",
        "uid",
        "last_modified_date_time",
        "red_alert",
        "yellow_alert",
        "middle_name",
        "email",
        "mobile_phone",
        "home_phone",
        "work_phone",
        "account_balance",
        "address_line_1",
        "address_line_2",
        "city",
        "postal_code",
        "work_extension",
        "referred_by",
        "photo_url",
        "emergency_contact_info_name",
        "emergency_contact_info_email",
        "emergency_contact_info_phone",
        "emergency_contact_info_relationship",
        "gender",
        "last_formula_notes",
        "active",
        "status",
        "action",
        "send_account_emails",
        "send_account_texts",
        "send_promotional_emails",
        "send_promotional_texts",
        "send_schedule_emails",
        "send_schedule_texts",
    ];
    static $patients = [
        "appointment_gender_preference",
        "birth_date",
        "country",
        "creation_date",
        "first_appointment_date",
        "first_name",
        "is_company",
        "is_prospect",
        "last_name",
        "liability_release",
        "membership_icon",
        "mobile_provider",
        "notes",
        "state",
        "uid",
        "last_modified_date_time",
        "red_alert",
        "yellow_alert",
        "middle_name",
        "email",
        "mobile_phone",
        "home_phone",
        "work_phone",
        "account_balance",
        "address_line_1",
        "address_line_2",
        "city",
        "postal_code",
        "work_extension",
        "referred_by",
        "photo_url",
        "emergency_contact_info_name",
        "emergency_contact_info_email",
        "emergency_contact_info_phone",
        "emergency_contact_info_relationship",
        "gender",
        "last_formula_notes",
        "active",
        "status",
        "action",
        "send_account_emails",
        "send_account_texts",
        "send_promotional_emails",
        "send_promotional_texts",
        "send_schedule_emails",
        "send_schedule_texts",
    ];

    static $class =  [
        "class_schedule_id",
        "visits",
        "max_capacity",
        "web_capacity",
        "total_booked",
        "total_booked_waitlist",
        "web_booked",
        "semester_id",
        "is_canceled",
        "substitute",
        "active",
        "is_waitlist_available",
        "is_enrolled",
        "hide_cancel",
        "uid",
        "is_available",
        "start_date_time",
        "end_date_time",
        "last_modified_date_time",
        "booking_status",
        "virtual_stream_link",
    ];

    static $classVisit =  [
        "appointment_id",
        "appointment_gender_preference",
        "appointment_status",
        "class_id",
        "start_date_time",
        "end_date_time",
        "uid",
        "last_modified_date_time",
        "late_cancelled",
        "make_up",
        "name",
        "signed_in",
        "web_signup",
        "action",
    ];

    static $clientService =  [
        "active_date",
        "count",
        "current",
        "expiration_date",
        "uid",
        "product_id",
        "name",
        "payment_date",
        "remaining",
        "site_id",
        "action",
        "patient_id",
    ];

    static $clientPurchase =  [
        "uid",
        "sale_date",
        "sale_time",
        "sale_date_time",
        "patient_id",
        "description",
        "account_payment",
        "price",
        "amount_paid",
        "discount",
        "tax",
        "returned",
        "quantity"
    ];

    static $practitioners =  [
        "api",
        "uid",
        "first_name",
        "last_name",
        "speciality",
        "title",
        "email",

        "date_of_birth",
        "start_date",
        "gender",
        "mobile",
        "phone",
        "ordinary_earnings_rate_id",
        "payroll_calendar_id",
        "employee_id",
        "status",
        "updated_date_utc",

        "address",
        "appointment_instructor",
        "always_allow_double_booking",
        "bio",
        "city",
        "country",
        "home_phone",
        "independent_contractor",
        "is_male",
        "mobile_phone",
        "name",
        "postal_code",
        "class_teacher",
        "sort_order",
        "state",
        "work_phone",
        "image_url",
        "class_assistant",
        "class_assistant_2",
        "employment_start",
        "employment_end",
        "provider_i_ds",
        "rep",
        "rep_2",
        "rep_3",
        "rep_4",
        "rep_5",
        "rep_6",
        "appointments",
        "unavailabilities",
        "availabilities",
        "emp_id",
    ];

    static function arr($name)
    {
        $arrFields = [
            "client" => self::$client,
            "class" => self::$class,
            "classVisit" => self::$classVisit,
            "clientService" => self::$clientService,
            "clientPurchase" => self::$clientPurchase,
            "practitioner" => self::$practitioners
        ];

        return $arrFields[$name];
    }
}
